### PR TITLE
stop docker ignoring env file

### PR DESCRIPTION
**Pull request by Fedelaus**
You had your .env file ignored so COPY wouldn't pick it up.

https://stackoverflow.com/questions/42132475/hidden-file-env-not-copied-using-docker-copy

### CODE REVIEW

**Comment by drph4nt0m** [comment]
Yeah. But isn't adding it to .dockerignore safe practice?

**Comment by Fedelaus** [comment]
@drph4nt0m when you run `docker build .` you are baking a selection of files into your image, if you wish your `.env` settings to exist at the time you run the image they must also be baked in.

Are you trying to achieve a development workflow or a package you can just `docker run <container-name>`? The latter must have this.

**Comment by drph4nt0m** [comment]
I just want to run the docker image on GCP.

**Comment by Fedelaus** [comment]
I think you should use a UI on GCP (Google Cloud Platform I assume?) to manage that.

Else, if you're using a private docker container registry, you could probably bake the env file into your image.

**Comment by drph4nt0m** [comment]
private docker container registry means? sorry I am new to docker.

**Comment by drph4nt0m** [comment]
@all-contributors please add @Fedelaus for code

**Pull request merged**
